const GRID_ROUTE_ACTION = "grdRoute";
const GRID_DELETE_ACTION = "grdDelete";
const GRID_ADD_ACTION = "grdAdd";
const GRID_UPDATE_ACTION = "grdUpdate";
const GRID_MOVEUP_ACTION = "grdMoveUp";
const GRID_MOVEDOWN_ACTION = "grdMoveDown";

module.exports = {
  GRID_ROUTE_ACTION,
  GRID_DELETE_ACTION,
  GRID_ADD_ACTION,
  GRID_UPDATE_ACTION,
  GRID_MOVEUP_ACTION,
  GRID_MOVEDOWN_ACTION,
};
